In [ ]:
a = "0123456"
a.find('1')

1

In [ ]:
3 + 2 * 2

7

In [ ]:
name = 'Lizz'
print(name[0:2])

Li


In [ ]:
A=(0,1,2,3) 
A[-1]

3

In [ ]:
S={'A','B','C'}

U={'A','Z','C'}


In [ ]:
D={'a':0,'b':1,'c':2}
D.values()

X={'a':0,'b':1,'c':2}
X['b'] 

1

In [ ]:
x=3

y=1

while(y!= x):
  print(y)
  y=y+1

1
2


In [ ]:
def f(*x):
  return sum(c)

In [ ]:
import numpy as np

n1=np.array([1,-1])
n2=np.array([1,1])
n1*n2

array([ 1, -1])

In [ ]:
import numpy as np
np.dot(np.array([1,-1]),np.array([1,1]))
A=np.array([[1,2],[3,4],[5,6],[7,8]])
A




array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
import numpy as np
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [ ]:
import numpy as np
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [ ]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool